---
ai_context_version: 1.1

project:
  name: leitstand
  summary: "Dashboard and control-room for the heimgewebe organism - daily system digest generator."
  role: dashboard_and_digest_generator
  primary_language: typescript
  visibility: internal

heimgewebe:
  axis:
    - UI
  fleet:
    enabled: true
  wgx:
    profile_expected: true
    guard_smoke_expected: true

interfaces:
  consumes:
    - "event.line"
    - "fleet.health"
    - "insights.daily"
  produces:
    - "insights.digest"
    - "dashboard.view"

dependencies:
  internal:
    - name: metarepo
      relationship: uses
      interface: [docs, templates]
    - name: wgx
      relationship: consumes
      interface: [fleet.health]
    - name: semantAH
      relationship: consumes
      interface: [insights.daily]
    - name: chronik
      relationship: consumes
      interface: [event.line]
  external:
    - name: node
      version: ">=18.0.0"
    - name: pnpm
      version: ">=8.0.0"

contracts:
  schemas: []
  # No local schemas; relies on canonical schemas from metarepo or external contracts.

architecture:
  entrypoints:
    - "src/cli.ts"
    - "src/server.ts"
  key_paths:
    - path: "src/fixtures/"
      purpose: "Static data for UI (e.g. observatory.json)"
    - path: "src/views/"
      purpose: "EJS templates for the web server"
  data_flow:
    input: "Consumes fleet.health, insights.daily, and event.line files."
    processing: "Aggregates data into daily digests and serves dashboard views."
    output: "Displays dashboard UI and generates digest files."

boundaries:
  not_responsible_for:
    - "Generating raw insights (responsibility of specialized agents)"
    - "Executing motorik actions (except for self-healing if needed)"
    - "UI repo is profile-free by policy."
    - "Don’t add .wgx/profile.yml unless policy changes."
  dangerous_assumptions:
    - "Assuming all data sources are always present (must handle missing files gracefully)"
    - "Assume npm; repo uses pnpm (see packageManager/pnpm-lock.yaml)."

conventions:
  branching: "main, feature/*"
  commit_prefix: "LEITSTAND"
  ci_platform: github_actions

documentation:
  runbook: docs/data-flow.md

ai_guidance:
  do:
    - "Ensure data loading logic prioritizes filename timestamps over mtime."
    - "Validate incoming data against canonical schemas where possible."
  dont:
    - "Hardcode data paths without flexibility for historical processing."
    - "Modify external schemas to fit the application."
