
from playwright.sync_api import sync_playwright
import os

def run():
    with sync_playwright() as p:
        browser = p.chromium.launch()
        page = browser.new_page()
        # Open the static file generated by build:static
        page.goto('file:///app/dist/site/observatory/index.html')
        page.screenshot(path='/app/verification/observatory_fixture_fix.png', full_page=True)
        browser.close()
        print('Screenshot saved to verification/observatory_fixture_fix.png')

if __name__ == '__main__':
    run()
