name: validate-leitstand-fixtures
permissions:
  contents: read

on:
  push:
  pull_request:

jobs:
  fixtures:
    name: fixtures (tests/fixtures/leitstand.jsonl)
    if: hashFiles('tests/fixtures/leitstand.jsonl') != ''
    uses: heimgewebe/metarepo/.github/workflows/reusable-validate-jsonl.yml@codex/add-github-workflows
    with:
      jsonl_path: tests/fixtures/leitstand.jsonl
      schema_url: https://raw.githubusercontent.com/heimgewebe/metarepo/main/contracts/leitstand-fixtures.schema.json
      strict: false
      validate_formats: true

  demo:
    name: demo (demo/leitstand.jsonl)
    if: hashFiles('demo/leitstand.jsonl') != ''
    uses: heimgewebe/metarepo/.github/workflows/reusable-validate-jsonl.yml@codex/add-github-workflows
    with:
      jsonl_path: demo/leitstand.jsonl
      schema_url: https://raw.githubusercontent.com/heimgewebe/metarepo/main/contracts/leitstand-fixtures.schema.json
      strict: false
      validate_formats: true
